version: "3.9"

services:
  web:
    # build: .
    image: erinamiller/cloudtodo
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    links:
      - "mongodb:db"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - ./db:/data/db:rw
      - ./dbconfig:/data/configdb:rw